//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custome
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string province { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}
